version: '3'
services:
  ms-0:
    image: nachocode/experiments-suite:cache
    networks:
      - my-net
    volumes:
      - ./target/test/logs:/app/logs:rw
      - ./target/test/workloads:/app/workloads:rw
      - ./target/test/source:/app/source:rw
      - ./target/test/sink:/app/sink:rw
    environment:
      - NODE_ID=ex-0
      - WORKLOAD_PATH=/app/workloads
      - WORKLOAD_FILENAME=workload_cache_0.csv
      - STATIC_EXTENSION=bin
      - SOURCE_FOLDER=/app/source
      - SINK_FOLDER=/app/sink
      - CACHE_NODES.0.host=172.18.0.3
      - CACHE_NODES.0.port=80
      - LOG_PATH=/app/logs

networks:
  my-net:
    external: true
